{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "hidden_units", "default": 8, "conditions": [], "values": [8, 16], "ordered": true}}, {"class_name": "Choice", "config": {"name": "num_heads", "default": 1, "conditions": [], "values": [1], "ordered": true}}, {"class_name": "Choice", "config": {"name": "dropout_rate", "default": 0.0, "conditions": [], "values": [0.0], "ordered": true}}, {"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "gelu"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "use_batch_norm", "default": 0, "conditions": [], "values": [0, 1], "ordered": true}}, {"class_name": "Choice", "config": {"name": "num_lstm_layers", "default": 1, "conditions": [], "values": [1], "ordered": true}}, {"class_name": "Choice", "config": {"name": "lstm_units", "default": 16, "conditions": [], "values": [16], "ordered": true}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.001], "ordered": true}}], "values": {"hidden_units": 8, "num_heads": 1, "dropout_rate": 0.0, "activation": "gelu", "use_batch_norm": 0, "num_lstm_layers": 1, "lstm_units": 16, "learning_rate": 0.001}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\Daniel\\Anaconda3\\envs\\watex\\lib\\site-packages\\keras\\src\\engine\\data_adapter.py\", line 1105, in select_data_adapter\n    raise ValueError(\nValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {\"<class 'NoneType'>\", \"<class 'tensorflow.python.framework.ops.EagerTensor'>\"}), <class 'tensorflow.python.framework.ops.EagerTensor'>\n"}